export const API_PATH: any = {
    'Commaon_Path':'https://mongowithnode.herokuapp.com/',
    'API_VERSION_V1': 'api/userModel/',
    'login': 'users/login',
    'registration': 'users',
    'testtokenheader': 'users/me',
    'logout': 'users/me/logout',
    'Save_DoctorProfile': 'Save_DoctorProfile',
    'Get_DoctorsList': 'Get_DoctorsList',
    'Save_PatientProfile': 'Save_PatientProfile',
    'Get_PatientsList': 'Get_PatientsList',
    'Delete_Doctor': 'Delete_Doctor',
    'Delete_Patient': 'Delete_Patient',
    'Delete_Pharmacist': 'Delete_Pharmacist',
    'Delete_Nurse': 'Delete_Nurse',
    'Delete_Physio': 'Delete_Physio',
    'Save_VisitCompleteIntimation': 'Save_VisitCompleteIntimation',
    'Save_PatMedForHomDel': 'Save_PatMedForHomDel',
    'Save_PharmacistVisitCompleteIntimation': 'Save_PharmacistVisitCompleteIntimation',
    'Save_PharmacistProfile': 'Save_PharmacistProfile',
    'Save_NurseProfile': 'Save_NurseProfile',
    'Save_PhysioProfile': 'Save_PhysioProfile',
    'Get_PharmacistsList': 'Get_PharmacistsList',
    'Get_NursesList': 'Get_NursesList',
    'Get_PhysiosList': 'Get_PhysiosList',
}