export const API_PATH: any = {
     'Commaon_Path':'https://mongowithnode.herokuapp.com/',
    //   'Commaon_Path':'http://localhost:5000/',
    'GTM_ID': 'GTM-M476F8N',
    'API_VERSION_V1': 'api/userModel/',
    'login': 'users/login',
    'registration': 'users',
    'userme': 'users/me',
    'logout': 'users/me/logout',
    'Get_DoctorProfile': 'Get_DoctorProfile',
    'Save_DoctorProfile': 'Save_DoctorProfile',
    'Update_DoctorProfile': 'Update_DoctorProfile',
    'Get_DoctorsList': 'Get_DoctorsList',
    'Save_PatientProfile': 'Save_PatientProfile',
    'Get_PatientProfile': 'Get_PatientProfile',
    'Update_PatientProfile': 'Update_PatientProfile',
    'Get_PatientsList': 'Get_PatientsList',
    'Delete_Doctor': 'Delete_Doctor',
    'Delete_Patient': 'Delete_Patient',
    'Delete_Pharmacist': 'Delete_Pharmacist',
    'Delete_Nurse': 'Delete_Nurse',
    'Delete_Physio': 'Delete_Physio',
    'Save_VisitCompleteIntimation': 'Save_VisitCompleteIntimation',
    'Request_PatientMedicinesHomeDelivery': 'Request_PatientMedicinesHomeDelivery',
    'Save_PharmaVisitCompleteIntimation': 'Save_PharmaVisitCompleteIntimation',
    'Save_PharmacistProfile': 'Save_PharmacistProfile',
    'Get_PharmacistProfile':'Get_PharmacistProfile',
    'Update_PharmacistProfile': 'Update_PharmacistProfile',
    'Save_NurseProfile': 'Save_NurseProfile',
    'Update_NurseProfile': 'Update_NurseProfile',
    'Get_NurseProfile': 'Get_NurseProfile',
    'Save_PhysioProfile': 'Save_PhysioProfile',
    'Update_PhysioProfile': 'Update_PhysioProfile',
    'Get_PharmacistsList': 'Get_PharmacistsList',
    'Get_NursesList': 'Get_NursesList',
    'Get_PhysiosList': 'Get_PhysiosList',
    'Get_PhysioProfile': 'Get_PhysioProfile',
    'Save_BookAppointment': 'Save_BookAppointment',
    'Get_FilteredDoctors': 'Get_FilteredDoctors',
    'Get_AppointmentsByDocID': 'Get_AppointmentsByDocID',
    'getFilteredAppointments': 'getFilteredAppointments',
    'Save_Disease': 'Save_Disease',
    'Get_DiseasesList': 'Get_DiseasesList',
    'Get_ExpertiseList': 'Get_ExpertiseList',
    'Save_Expertise': 'Save_Expertise',
    'Save_Medicine': 'Save_Medicine',
    'Get_MedicinesList': 'Get_MedicinesList',
    'Get_PharmaReqByPhamacistID': 'Get_PharmaReqByPhamacistID',
    'Get_AppointmentsByPatientID': 'Get_AppointmentsByPatientID',
    'Get_LabTestsList': 'Get_LabTestsList',
    'Save_LabTestsPackage': 'Save_LabTestsPackage',
    'Save_Image': 'api/photo',
    'Get_LabTestsPackage': 'Get_LabTestsPackage',
    'Save_BookLabTest': 'Save_BookLabTest',
    'Save_LabTest': 'Save_LabTest',
    'Get_CommonDashboardCount': 'Get_CommonDashboardCount',
    'Get_DiseaseWiseApptCount': 'Get_DiseaseWiseApptCount',
    'Get_MedicineWiseApptCount': 'Get_MedicineWiseApptCount',
    'Get_PharmacistWiseApptCount': 'Get_PharmacistWiseApptCount',
    'Get_DoctorWiseApptCount': 'Get_DoctorWiseApptCount',
    'Get_LabTestWiseTestCount': 'Get_LabTestWiseTestCount',
    'Get_IndividualToPackageLabTestCount': 'Get_IndividualToPackageLabTestCount',
    'Get_MonthlyHomeOnlineApptCount': 'Get_MonthlyHomeOnlineApptCount',
    'Delete_LabTest': 'Delete_LabTest',
    'Delete_LabTestPackage': 'Delete_LabTestPackage',
    'Get_LabTestsBookings': 'Get_LabTestsBookings',
    'Get_LabTechniciansList': 'Get_LabTechniciansList',
    'Get_LabTechnicianProfile': 'Get_LabTechnicianProfile',
    'Update_LabTechnicianProfile': 'Update_LabTechnicianProfile',
    'Save_UploadLabTestReport': 'Save_UploadLabTestReport',
    'Get_UploadedTestReportbyLabTestID': 'Get_UploadedTestReportbyLabTestID',
    'GenerateOTP': 'GenerateOTP',
    'ChangePassword': 'users/changePassword',
    'Get_WebsiteImageByLocationEnum': 'Get_WebsiteImageByLocationEnum',
    'SaveUpdate_UploadWebsiteImages': 'SaveUpdate_UploadWebsiteImages',
    'Forgot_Password': 'users/forgotPassword',
    'Get_WebsiteImageByLocationEnumList': 'Get_WebsiteImageByLocationEnumList',
    'Delete_LabTestsPackage': 'Delete_LabTestsPackage',
    'Delete_LabTechnician': 'Delete_LabTechnician',
    
}

export const PATTERN_ERROR_MESSAGE = {
    password: 'Password must contain one letter,one number and one special character and length should be 6 to 20 characters.',
    email: 'Invalid Email id',
    billingRate: 'Invalid Billing rate. It should be upto 2 decimal only.',
    companyId: 'Only alphabets, numbers and special character (),-,. are allowed. ',
    companyAdminUserId: 'Only alphabets, numbers and special character (),-,.,@ are allowed.',
    storeCode: 'Only alphabets, numbers and special character (),-,. are allowed. ',
    storeName: 'Only alphabets, numbers and special character (),-,. are allowed. ',
    firstName: 'Only alphabets, numbers and special character _,. are allowed. ',
    lastName: 'Only alphabets, numbers and special character _,. are allowed. ',
    name: 'Only alphabets, numbers, space and special character _,. are allowed. ',
    gstNo: 'Only alphabets and numbers are allowed',
    panNo: 'Only alphabets and numbers are allowed',
    phoneno:'Ten Character allowed'
}
export const LoginError={
    inactiveUserMSG:'Login failed! This is an InActive Account !! To Deactivate, register with same credentials'
}


